In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt 
import seaborn as sns
import sklearn

In [2]:
df=pd.read_csv('houses.csv')
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [3]:
# 1. Determine the no. of rows and no. of columns in the dataset

In [4]:
df.columns.value_counts().sum()

21

In [5]:
index=df.index
rows=len(index)
rows

23678

In [6]:
# 2. Display the datatypes of each column

In [7]:
df.dtypes

Suburb            object
Address           object
Rooms            float64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [8]:
# 3. Determine the row indexes of rows having all null values (i.e. empty rows)

In [9]:
df.index.isnull().sum()

0

In [10]:
# 4. Determine the total number of empty rows and their percentage in whole dataset and remove them.

In [11]:
# 5. Determine the column names having missing values.

In [12]:
df.isnull().sum()

Suburb             131
Address            131
Rooms              131
Type               131
Price             5282
Method             131
SellerG            131
Date               131
Distance           132
Postcode           132
Bedroom2          4612
Bathroom          4615
Car               4757
Landsize          6268
BuildingArea     13660
YearBuilt        12138
CouncilArea       8022
Lattitude         4435
Longtitude        4435
Regionname         132
Propertycount      132
dtype: int64

In [13]:
# 6. Determine the missing values and their percentage in each column.

In [14]:
df.isnull().mean()*100

Suburb            0.553256
Address           0.553256
Rooms             0.553256
Type              0.553256
Price            22.307627
Method            0.553256
SellerG           0.553256
Date              0.553256
Distance          0.557480
Postcode          0.557480
Bedroom2         19.477996
Bathroom         19.490666
Car              20.090379
Landsize         26.471830
BuildingArea     57.690683
YearBuilt        51.262776
CouncilArea      33.879551
Lattitude        18.730467
Longtitude       18.730467
Regionname        0.557480
Propertycount     0.557480
dtype: float64

In [15]:
percent_missing= df.isnull().sum()*100/len(df)
percent_missing

Suburb            0.553256
Address           0.553256
Rooms             0.553256
Type              0.553256
Price            22.307627
Method            0.553256
SellerG           0.553256
Date              0.553256
Distance          0.557480
Postcode          0.557480
Bedroom2         19.477996
Bathroom         19.490666
Car              20.090379
Landsize         26.471830
BuildingArea     57.690683
YearBuilt        51.262776
CouncilArea      33.879551
Lattitude        18.730467
Longtitude       18.730467
Regionname        0.557480
Propertycount     0.557480
dtype: float64

In [16]:
missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 'percent_missing': percent_missing})
missing_value_df

                 column_name  percent_missing
Suburb                Suburb         0.553256
Address              Address         0.553256
Rooms                  Rooms         0.553256
Type                    Type         0.553256
Price                  Price        22.307627
Method                Method         0.553256
SellerG              SellerG         0.553256
Date                    Date         0.553256
Distance            Distance         0.557480
Postcode            Postcode         0.557480
Bedroom2            Bedroom2        19.477996
Bathroom            Bathroom        19.490666
Car                      Car        20.090379
Landsize            Landsize        26.471830
BuildingArea    BuildingArea        57.690683
YearBuilt          YearBuilt        51.262776
CouncilArea      CouncilArea        33.879551
Lattitude          Lattitude        18.730467
Longtitude        Longtitude        18.730467
Regionname        Regionname         0.557480
Propertycount  Propertycount         0.557480

In [17]:
#7. Determine the row indexes having missing values.

0 Suburb : The null values can be replaced
1 Address : The null values can be replaced
2 Rooms : The null values can be replaced
3 Type : The null values can be replaced
4 Price : The null values can be replaced
5 Method : The null values can be replaced
6 SellerG : The null values can be replaced
7 Date : The null values can be replaced
8 Distance : The null values can be replaced
9 Postcode : The null values can be replaced
10 Bedroom2 : The null values can be replaced
11 Bathroom : The null values can be replaced
12 Car : The null values can be replaced
13 Landsize : The null values can be replaced
14 BuildingArea :The null values can't be replaced
15 YearBuilt :The null values can't be replaced
16 CouncilArea : The null values can be replaced
17 Lattitude : The null values can be replaced
18 Longtitude : The null values can be replaced
19 Regionname : The null values can be replaced
20 Propertycount : The null values can be replaced

In [29]:
df[df['Suburb'].isnull()].index.tolist()

[31,
 1145,
 1348,
 2119,
 3277,
 3288,
 3745,
 3752,
 3798,
 3855,
 4089,
 4096,
 4164,
 4218,
 4222,
 4326,
 4649,
 4897,
 4942,
 5052,
 5223,
 5265,
 5328,
 5331,
 5383,
 5405,
 5625,
 5741,
 5952,
 6125,
 6133,
 6140,
 6143,
 6251,
 6326,
 6406,
 6446,
 6703,
 6717,
 6853,
 6921,
 7086,
 7261,
 7348,
 7596,
 7743,
 7759,
 7762,
 7775,
 8054,
 8095,
 8118,
 8190,
 8409,
 8501,
 8652,
 8816,
 8974,
 9098,
 9210,
 9232,
 9450,
 9455,
 9586,
 9761,
 9888,
 9894,
 10009,
 10125,
 10390,
 10475,
 10738,
 10952,
 11334,
 11348,
 11552,
 11755,
 12087,
 12441,
 12559,
 12997,
 13066,
 13381,
 13647,
 13725,
 14009,
 14471,
 14644,
 14963,
 15094,
 15214,
 15771,
 16044,
 16252,
 16563,
 16655,
 16848,
 17111,
 17246,
 17611,
 17741,
 18077,
 18148,
 18251,
 18374,
 18476,
 18547,
 18671,
 18742,
 18884,
 19001,
 19287,
 19641,
 19949,
 20087,
 20422,
 20496,
 20695,
 20838,
 20880,
 21055,
 21220,
 21343,
 21602,
 22003,
 22109,
 22288,
 22704,
 22918,
 23153,
 23341]

In [36]:
[df['Suburb'].isnull()[1145]]

[True]

In [ ]:
#7. Determine the row indexes having missing values.

In [49]:
null=df[df.isnull().any(axis=1)]
null

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81140,145.01160,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3.0,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4.0,h,NaN,SN,Nelson,06-08-2016,2.5,3067.0,...,2.0,2.0,400.0,220.0,2006.0,Yarra,-37.79650,144.99650,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [ ]:
#8. Determine the missing values and their percentage in each row.

In [60]:
for i in range(len(df.index)):
    print(" Total NaN in row", i, ":", 
          df.iloc[i].isnull().sum())

 Total NaN in row 0 : 3
 Total NaN in row 1 : 2
 Total NaN in row 2 : 0
 Total NaN in row 3 : 3
 Total NaN in row 4 : 0
 Total NaN in row 5 : 2
 Total NaN in row 6 : 0
 Total NaN in row 7 : 1
 Total NaN in row 8 : 2
 Total NaN in row 9 : 2
 Total NaN in row 10 : 2
 Total NaN in row 11 : 0
 Total NaN in row 12 : 1
 Total NaN in row 13 : 1
 Total NaN in row 14 : 0
 Total NaN in row 15 : 9
 Total NaN in row 16 : 9
 Total NaN in row 17 : 2
 Total NaN in row 18 : 0
 Total NaN in row 19 : 9
 Total NaN in row 20 : 1
 Total NaN in row 21 : 9
 Total NaN in row 22 : 9
 Total NaN in row 23 : 2
 Total NaN in row 24 : 0
 Total NaN in row 25 : 0
 Total NaN in row 26 : 7
 Total NaN in row 27 : 9
 Total NaN in row 28 : 2
 Total NaN in row 29 : 2
 Total NaN in row 30 : 0
 Total NaN in row 31 : 21
 Total NaN in row 32 : 1
 Total NaN in row 33 : 0
 Total NaN in row 34 : 9
 Total NaN in row 35 : 10
 Total NaN in row 36 : 0
 Total NaN in row 37 : 2
 Total NaN in row 38 : 0
 Total NaN in row 39 : 0
 Total NaN in row 40 : 1
 Total NaN in row 41 : 1
 Total NaN in row 42 : 1
 Total NaN in row 43 : 0
 Total NaN in row 44 : 0
 Total NaN in row 45 : 0
 Total NaN in row 46 : 9
 Total NaN in row 47 : 9
 Total NaN in row 48 : 8
 Total NaN in row 49 : 2
 Total NaN in row 50 : 0
 Total NaN in row 51 : 1
 Total NaN in row 52 : 0
 Total NaN in row 53 : 9
 Total NaN in row 54 : 2
 Total NaN in row 55 : 7
 Total NaN in row 56 : 1
 Total NaN in row 57 : 0
 Total NaN in row 58 : 0
 Total NaN in row 59 : 0
 Total NaN in row 60 : 0
 Total NaN in row 61 : 10
 Total NaN in row 62 : 0
 Total NaN in row 63 : 9
 Total NaN in row 64 : 0
 Total NaN in row 65 : 8
 Total NaN in row 66 : 9
 Total NaN in row 67 : 0
 Total NaN in row 68 : 0
 Total NaN in row 69 : 0
 Total NaN in row 70 : 1
 Total NaN in row 71 : 0
 Total NaN in row 72 : 0
 Total NaN in row 73 : 0
 Total NaN in row 74 : 0
 Total NaN in row 75 : 9
 Total NaN in row 76 : 9
 Total NaN in row 77 : 9
 Total NaN in row 78 : 9
 Total NaN in row 79 : 9
 Total NaN in row 80 : 2
 Total NaN in row 81 : 1
 Total NaN in row 82 : 0
 Total NaN in row 83 : 0
 Total NaN in row 84 : 0
 Total NaN in row 85 : 9
 Total NaN in row 86 : 0
 Total NaN in row 87 : 0
 Total NaN in row 88 : 9
 Total NaN in row 89 : 0
 Total NaN in row 90 : 9
 Total NaN in row 91 : 0
 Total NaN in row 92 : 9
 Total NaN in row 93 : 9
 Total NaN in row 94 : 9
 Total NaN in row 95 : 2
 Total NaN in row 96 : 9
 Total NaN in row 97 : 2
 Total NaN in row 98 : 9
 Total NaN in row 99 : 0
 Total NaN in row 100 : 9
 Total NaN in row 101 : 0
 Total NaN in row 102 : 1
 Total NaN in row 103 : 2
 Total NaN in row 104 : 0
 Total NaN in row 105 : 0
 Total NaN in row 106 : 2
 Total NaN in row 107 : 0
 Total NaN in row 108 : 9
 Total NaN in row 109 : 0
 Total NaN in row 110 : 0
 Total NaN in row 111 : 2
 Total NaN in row 112 : 9
 Total NaN in row 113 : 0
 Total NaN in row 114 : 0
 Total NaN in row 115 : 0
 Total NaN in row 116 : 9
 Total NaN in row 117 : 2
 Total NaN in row 118 : 1
 Total NaN in row 119 : 2
 Total NaN in row 120 : 2
 Total NaN in row 121 : 2
 Total NaN in row 122 : 10
 Total NaN in row 123 : 2
 Total NaN in row 124 : 9
 Total NaN in row 125 : 9
 Total NaN in row 126 : 9
 Total NaN in row 127 : 9
 Total NaN in row 128 : 9
 Total NaN in row 129 : 2
 Total NaN in row 130 : 0
 Total NaN in row 131 : 9
 Total NaN in row 132 : 9
 Total NaN in row 133 : 9
 Total NaN in row 134 : 0
 Total NaN in row 135 : 2
 Total NaN in row 136 : 0
 Total NaN in row 137 : 0
 Total NaN in row 138 : 2
 Total NaN in row 139 : 0
 Total NaN in row 140 : 1
 Total NaN in row 141 : 1
 Total NaN in row 142 : 2
 Total NaN in row 143 : 0
 Total NaN in row 144 : 1
 Total NaN in row 145 : 2
 Total NaN in row 146 : 0
 Total NaN in row 147 : 9
 Total NaN in row 148 : 0
 Total NaN in row 149 : 2
 Total NaN in row 150 : 0
 Total NaN in row 151 : 1
 Total NaN in row 152 : 2
 Total NaN in row 153 : 0
 Total NaN in row 154 : 2
 Total NaN in row 155 : 2
 Total NaN in row 156 : 0
 Total NaN in row 157 : 2
 Total NaN in row 158 : 1
 Total NaN in row 159 : 2
 Total NaN in row 160 : 0
 Total NaN in row 161 : 3
 Total NaN in row 162 : 0
 Total NaN in row 163 : 0
 Total NaN in row 164 : 3
 Total NaN in row 165 : 3
 Total NaN in row 166 : 1
 Total NaN in row 167 : 0
 Total NaN in row 168 : 3
 Total NaN in row 169 : 0
 Total NaN in row 170 : 3
 Total NaN in row 171 : 2
 Total NaN in row 172 : 3
 Total NaN in row 173 : 0
 Total NaN in row 174 : 1
 Total NaN in row 175 : 3
 Total NaN in row 176 : 3
 Total NaN in row 177 : 0
 Total NaN in row 178 : 0
 Total NaN in row 179 : 0
 Total NaN in row 180 : 2
 Total NaN in row 181 : 2
 Total NaN in row 182 : 2
 Total NaN in row 183 : 2
 Total NaN in row 184 : 0
 Total NaN in row 185 : 9
 Total NaN in row 186 : 2
 Total NaN in row 187 : 0
 Total NaN in row 188 : 1
 Total NaN in row 189 : 1
 Total NaN in row 190 : 3
 Total NaN in row 191 : 2
 Total NaN in row 192 : 0
 Total NaN in row 193 : 2
 Total NaN in row 194 : 0
 Total NaN in row 195 : 1
 Total NaN in row 196 : 0
 Total NaN in row 197 : 1
 Total NaN in row 198 : 2
 Total NaN in row 199 : 9
 Total NaN in row 200 : 3
 Total NaN in row 201 : 9
 Total NaN in row 202 : 0
 Total NaN in row 203 : 0
 Total NaN in row 204 : 2
 Total NaN in row 205 : 0
 Total NaN in row 206 : 0
 Total NaN in row 207 : 2
 Total NaN in row 208 : 10
 Total NaN in row 209 : 9
 Total NaN in row 210 : 2
 Total NaN in row 211 : 2
 Total NaN in row 212 : 10
 Total NaN in row 213 : 9
 Total NaN in row 214 : 2
 Total NaN in row 215 : 0
 Total NaN in row 216 : 0
 Total NaN in row 217 : 0
 Total NaN in row 218 : 0
 Total NaN in row 219 : 2
 Total NaN in row 220 : 0
 Total NaN in row 221 : 7
 Total NaN in row 222 : 3
 Total NaN in row 223 : 9
 Total NaN in row 224 : 9
 Total NaN in row 225 : 2
 Total NaN in row 226 : 9
 Total NaN in row 227 : 0
 Total NaN in row 228 : 1
 Total NaN in row 229 : 2
 Total NaN in row 230 : 0
 Total NaN in row 231 : 0
 Total NaN in row 232 : 0
 Total NaN in row 233 : 0
 Total NaN in row 234 : 0
 Total NaN in row 235 : 2
 Total NaN in row 236 : 0
 Total NaN in row 237 : 0
 Total NaN in row 238 : 2
 Total NaN in row 239 : 0
 Total NaN in row 240 : 2
 Total NaN in row 241 : 9
 Total NaN in row 242 : 0
 Total NaN in row 243 : 0
 Total NaN in row 244 : 1
 Total NaN in row 245 : 0
 Total NaN in row 246 : 2
 Total NaN in row 247 : 0
 Total NaN in row 248 : 2
 Total NaN in row 249 : 1
 Total NaN in row 250 : 0
 Total NaN in row 251 : 2
 Total NaN in row 252 : 0
 Total NaN in row 253 : 9
 Total NaN in row 254 : 1
 Total NaN in row 255 : 9
 Total NaN in row 256 : 0
 Total NaN in row 257 : 9
 Total NaN in row 258 : 1
 Total NaN in row 259 : 2
 Total NaN in row 260 : 0
 Total NaN in row 261 : 2
 Total NaN in row 262 : 0
 Total NaN in row 263 : 0
 Total NaN in row 264 : 2
 Total NaN in row 265 : 0
 Total NaN in row 266 : 2
 Total NaN in row 267 : 9
 Total NaN in row 268 : 2
 Total NaN in row 269 : 2
 Total NaN in row 270 : 0
 Total NaN in row 271 : 3
 Total NaN in row 272 : 2
 Total NaN in row 273 : 2
 Total NaN in row 274 : 9
 Total NaN in row 275 : 1
 Total NaN in row 276 : 2
 Total NaN in row 277 : 0
 Total NaN in row 278 : 2
 Total NaN in row 279 : 0
 Total NaN in row 280 : 2
 Total NaN in row 281 : 2
 Total NaN in row 282 : 1
 Total NaN in row 283 : 0
 Total NaN in row 284 : 1
 Total NaN in row 285 : 0
 Total NaN in row 286 : 0
 Total NaN in row 287 : 9
 Total NaN in row 288 : 9
 Total NaN in row 289 : 2
 Total NaN in row 290 : 0
 Total NaN in row 291 : 2
 Total NaN in row 292 : 10
 Total NaN in row 293 : 0
 Total NaN in row 294 : 10
 Total NaN in row 295 : 2
 Total NaN in row 296 : 0
 Total NaN in row 297 : 9
 Total NaN in row 298 : 9
 Total NaN in row 299 : 9
 Total NaN in row 300 : 0
 Total NaN in row 301 : 9
 Total NaN in row 302 : 0
 Total NaN in row 303 : 9
 Total NaN in row 304 : 9
 Total NaN in row 305 : 9
 Total NaN in row 306 : 10
 Total NaN in row 307 : 0
 Total NaN in row 308 : 9
 Total NaN in row 309 : 9
 Total NaN in row 310 : 1
 Total NaN in row 311 : 2
 Total NaN in row 312 : 9
 Total NaN in row 313 : 9
 Total NaN in row 314 : 1
 Total NaN in row 315 : 2
 Total NaN in row 316 : 9
 Total NaN in row 317 : 10
 Total NaN in row 318 : 10
 Total NaN in row 319 : 9
 Total NaN in row 320 : 9
 Total NaN in row 321 : 9
 Total NaN in row 322 : 0
 Total NaN in row 323 : 0
 Total NaN in row 324 : 9
 Total NaN in row 325 : 9
 Total NaN in row 326 : 2
 Total NaN in row 327 : 9
 Total NaN in row 328 : 9
 Total NaN in row 329 : 9
 Total NaN in row 330 : 9
 Total NaN in row 331 : 9
 Total NaN in row 332 : 9
 Total NaN in row 333 : 9
 Total NaN in row 334 : 9
 Total NaN in row 335 : 2
 Total NaN in row 336 : 1
 Total NaN in row 337 : 9
 Total NaN in row 338 : 1
 Total NaN in row 339 : 2
 Total NaN in row 340 : 0
 Total NaN in row 341 : 0
 Total NaN in row 342 : 9
 Total NaN in row 343 : 0
 Total NaN in row 344 : 0
 Total NaN in row 345 : 1
 Total NaN in row 346 : 9
 Total NaN in row 347 : 2
 Total NaN in row 348 : 2
 Total NaN in row 349 : 10
 Total NaN in row 350 : 0
 Total NaN in row 351 : 2
 Total NaN in row 352 : 9
 Total NaN in row 353 : 9
 Total NaN in row 354 : 2
 Total NaN in row 355 : 9
 Total NaN in row 356 : 2
 Total NaN in row 357 : 0
 Total NaN in row 358 : 9
 Total NaN in row 359 : 10
 Total NaN in row 360 : 2
 Total NaN in row 361 : 2
 Total NaN in row 362 : 0
 Total NaN in row 363 : 9
 Total NaN in row 364 : 9
 Total NaN in row 365 : 3
 Total NaN in row 366 : 0
 Total NaN in row 367 : 2
 Total NaN in row 368 : 0
 Total NaN in row 369 : 0
 Total NaN in row 370 : 1
 Total NaN in row 371 : 9
 Total NaN in row 372 : 0
 Total NaN in row 373 : 2
 Total NaN in row 374 : 9
 Total NaN in row 375 : 9
 Total NaN in row 376 : 0
 Total NaN in row 377 : 3
 Total NaN in row 378 : 2
 Total NaN in row 379 : 3
 Total NaN in row 380 : 10
 Total NaN in row 381 : 0
 Total NaN in row 382 : 3
 Total NaN in row 383 : 2
 Total NaN in row 384 : 0
 Total NaN in row 385 : 10
 Total NaN in row 386 : 1
 Total NaN in row 387 : 2
 Total NaN in row 388 : 1
 Total NaN in row 389 : 1
 Total NaN in row 390 : 9
 Total NaN in row 391 : 2
 Total NaN in row 392 : 3
 Total NaN in row 393 : 0
 Total NaN in row 394 : 2
 Total NaN in row 395 : 2
 Total NaN in row 396 : 1
 Total NaN in row 397 : 1
 Total NaN in row 398 : 1
 Total NaN in row 399 : 10
 Total NaN in row 400 : 1
 Total NaN in row 401 : 0
 Total NaN in row 402 : 1
 Total NaN in row 403 : 0
 Total NaN in row 404 : 2
 Total NaN in row 405 : 1
 Total NaN in row 406 : 2
 Total NaN in row 407 : 1
 Total NaN in row 408 : 0
 Total NaN in row 409 : 1
 Total NaN in row 410 : 0
 Total NaN in row 411 : 0
 Total NaN in row 412 : 1
 Total NaN in row 413 : 1
 Total NaN in row 414 : 1
 Total NaN in row 415 : 2
 Total NaN in row 416 : 1
 Total NaN in row 417 : 0
 Total NaN in row 418 : 10
 Total NaN in row 419 : 0
 Total NaN in row 420 : 10
 Total NaN in row 421 : 2
 Total NaN in row 422 : 3
 Total NaN in row 423 : 1
 Total NaN in row 424 : 10
 Total NaN in row 425 : 3
 Total NaN in row 426 : 2
 Total NaN in row 427 : 0
 Total NaN in row 428 : 1
 Total NaN in row 429 : 2
 Total NaN in row 430 : 2
 Total NaN in row 431 : 2
 Total NaN in row 432 : 2
 Total NaN in row 433 : 0
 Total NaN in row 434 : 10
 Total NaN in row 435 : 2
 Total NaN in row 436 : 1
 Total NaN in row 437 : 1
 Total NaN in row 438 : 2
 Total NaN in row 439 : 0
 Total NaN in row 440 : 1
 Total NaN in row 441 : 2
 Total NaN in row 442 : 0
 Total NaN in row 443 : 10
 Total NaN in row 444 : 10
 Total NaN in row 445 : 0
 Total NaN in row 446 : 0
 Total NaN in row 447 : 3
 Total NaN in row 448 : 3
 Total NaN in row 449 : 3
 Total NaN in row 450 : 2
 Total NaN in row 451 : 1
 Total NaN in row 452 : 9
 Total NaN in row 453 : 2
 Total NaN in row 454 : 0
 Total NaN in row 455 : 1
 Total NaN in row 456 : 0
 Total NaN in row 457 : 1
 Total NaN in row 458 : 0
 Total NaN in row 459 : 2
 Total NaN in row 460 : 1
 Total NaN in row 461 : 3
 Total NaN in row 462 : 0
 Total NaN in row 463 : 9
 Total NaN in row 464 : 10
 Total NaN in row 465 : 9
 Total NaN in row 466 : 0
 Total NaN in row 467 : 0
 Total NaN in row 468 : 0
 Total NaN in row 469 : 0
 Total NaN in row 470 : 3
 Total NaN in row 471 : 1
 Total NaN in row 472 : 2
 Total NaN in row 473 : 3
 Total NaN in row 474 : 0
 Total NaN in row 475 : 9
 Total NaN in row 476 : 1
 Total NaN in row 477 : 3
 Total NaN in row 478 : 9
 Total NaN in row 479 : 2
 Total NaN in row 480 : 2
 Total NaN in row 481 : 0
 Total NaN in row 482 : 2
 Total NaN in row 483 : 3
 Total NaN in row 484 : 1
 Total NaN in row 485 : 1
 Total NaN in row 486 : 2
 Total NaN in row 487 : 0
 Total NaN in row 488 : 0
 Total NaN in row 489 : 1
 Total NaN in row 490 : 9
 Total NaN in row 491 : 0
 Total NaN in row 492 : 0
 Total NaN in row 493 : 0
 Total NaN in row 494 : 1
 Total NaN in row 495 : 0
 Total NaN in row 496 : 0
 Total NaN in row 497 : 0
 Total NaN in row 498 : 0
 Total NaN in row 499 : 9
 Total NaN in row 500 : 0
 Total NaN in row 501 : 0
 Total NaN in row 502 : 0
 Total NaN in row 503 : 2
 Total NaN in row 504 : 0
 Total NaN in row 505 : 0
 Total NaN in row 506 : 1
 Total NaN in row 507 : 0
 Total NaN in row 508 : 3
 Total NaN in row 509 : 0
 Total NaN in row 510 : 2
 Total NaN in row 511 : 2
 Total NaN in row 512 : 9
 Total NaN in row 513 : 0
 Total NaN in row 514 : 9
 Total NaN in row 515 : 1
 Total NaN in row 516 : 0
 Total NaN in row 517 : 2
 Total NaN in row 518 : 1
 Total NaN in row 519 : 9
 Total NaN in row 520 : 0
 Total NaN in row 521 : 2
 Total NaN in row 522 : 1
 Total NaN in row 523 : 1
 Total NaN in row 524 : 1
 Total NaN in row 525 : 9
 Total NaN in row 526 : 0
 Total NaN in row 527 : 0
 Total NaN in row 528 : 0
 Total NaN in row 529 : 0
 Total NaN in row 530 : 9
 Total NaN in row 531 : 0
 Total NaN in row 532 : 0
 Total NaN in row 533 : 9
 Total NaN in row 534 : 0
 Total NaN in row 535 : 2
 Total NaN in row 536 : 9
 Total NaN in row 537 : 0
 Total NaN in row 538 : 0
 Total NaN in row 539 : 0
 Total NaN in row 540 : 0
 Total NaN in row 541 : 0
 Total NaN in row 542 : 0
 Total NaN in row 543 : 9
 Total NaN in row 544 : 0
 Total NaN in row 545 : 0
 Total NaN in row 546 : 2
 Total NaN in row 547 : 2
 Total NaN in row 548 : 2
 Total NaN in row 549 : 0
 Total NaN in row 550 : 1
 Total NaN in row 551 : 0
 Total NaN in row 552 : 2
 Total NaN in row 553 : 0
 Total NaN in row 554 : 0
 Total NaN in row 555 : 1
 Total NaN in row 556 : 0
 Total NaN in row 557 : 2
 Total NaN in row 558 : 0
 Total NaN in row 559 : 2
 Total NaN in row 560 : 2
 Total NaN in row 561 : 1
 Total NaN in row 562 : 9
 Total NaN in row 563 : 2
 Total NaN in row 564 : 1
 Total NaN in row 565 : 0
 Total NaN in row 566 : 0
 Total NaN in row 567 : 0
 Total NaN in row 568 : 1
 Total NaN in row 569 : 1
 Total NaN in row 570 : 0
 Total NaN in row 571 : 0
 Total NaN in row 572 : 9
 Total NaN in row 573 : 0
 Total NaN in row 574 : 0
 Total NaN in row 575 : 0
 Total NaN in row 576 : 2
 Total NaN in row 577 : 0
 Total NaN in row 578 : 0
 Total NaN in row 579 : 9
 Total NaN in row 580 : 0
 Total NaN in row 581 : 1
 Total NaN in row 582 : 7
 Total NaN in row 583 : 0
 Total NaN in row 584 : 1
 Total NaN in row 585 : 2
 Total NaN in row 586 : 2
 Total NaN in row 587 : 2
 Total NaN in row 588 : 0
 Total NaN in row 589 : 2
 Total NaN in row 590 : 2
 Total NaN in row 591 : 0
 Total NaN in row 592 : 0
 Total NaN in row 593 : 9
 Total NaN in row 594 : 9
 Total NaN in row 595 : 0
 Total NaN in row 596 : 2
 Total NaN in row 597 : 2
 Total NaN in row 598 : 0
 Total NaN in row 599 : 9
 Total NaN in row 600 : 0
 Total NaN in row 601 : 2
 Total NaN in row 602 : 0
 Total NaN in row 603 : 1
 Total NaN in row 604 : 1
 Total NaN in row 605 : 2
 Total NaN in row 606 : 9
 Total NaN in row 607 : 9
 Total NaN in row 608 : 0
 Total NaN in row 609 : 9
 Total NaN in row 610 : 10
 Total NaN in row 611 : 9
 Total NaN in row 612 : 10
 Total NaN in row 613 : 9
 Total NaN in row 614 : 9
 Total NaN in row 615 : 0
 Total NaN in row 616 : 0
 Total NaN in row 617 : 0
 Total NaN in row 618 : 1
 Total NaN in row 619 : 9
 Total NaN in row 620 : 0
 Total NaN in row 621 : 0
 Total NaN in row 622 : 3
 Total NaN in row 623 : 1
 Total NaN in row 624 : 0
 Total NaN in row 625 : 9
 Total NaN in row 626 : 9
 Total NaN in row 627 : 9
 Total NaN in row 628 : 1
 Total NaN in row 629 : 0
 Total NaN in row 630 : 9
 Total NaN in row 631 : 0
 Total NaN in row 632 : 3
 Total NaN in row 633 : 0
 Total NaN in row 634 : 1
 Total NaN in row 635 : 3
 Total NaN in row 636 : 2
 Total NaN in row 637 : 9
 Total NaN in row 638 : 9
 Total NaN in row 639 : 9
 Total NaN in row 640 : 3
 Total NaN in row 641 : 10
 Total NaN in row 642 : 3
 Total NaN in row 643 : 0
 Total NaN in row 644 : 9
 Total NaN in row 645 : 1
 Total NaN in row 646 : 2
 Total NaN in row 647 : 0
 Total NaN in row 648 : 9
 Total NaN in row 649 : 2
 Total NaN in row 650 : 9
 Total NaN in row 651 : 0
 Total NaN in row 652 : 1
 Total NaN in row 653 : 9
 Total NaN in row 654 : 10
 Total NaN in row 655 : 0
 Total NaN in row 656 : 3
 Total NaN in row 657 : 9
 Total NaN in row 658 : 9
 Total NaN in row 659 : 9
 Total NaN in row 660 : 0
 Total NaN in row 661 : 9
 Total NaN in row 662 : 10
 Total NaN in row 663 : 1
 Total NaN in row 664 : 0
 Total NaN in row 665 : 10
 Total NaN in row 666 : 0
 Total NaN in row 667 : 0
 Total NaN in row 668 : 0
 Total NaN in row 669 : 2
 Total NaN in row 670 : 0
 Total NaN in row 671 : 0
 Total NaN in row 672 : 1
 Total NaN in row 673 : 2
 Total NaN in row 674 : 0
 Total NaN in row 675 : 0
 Total NaN in row 676 : 2
 Total NaN in row 677 : 2
 Total NaN in row 678 : 0
 Total NaN in row 679 : 9
 Total NaN in row 680 : 2
 Total NaN in row 681 : 1
 Total NaN in row 682 : 3
 Total NaN in row 683 : 2
 Total NaN in row 684 : 10
 Total NaN in row 685 : 2
 Total NaN in row 686 : 0
 Total NaN in row 687 : 0
 Total NaN in row 688 : 1
 Total NaN in row 689 : 0
 Total NaN in row 690 : 2
 Total NaN in row 691 : 0
 Total NaN in row 692 : 0
 Total NaN in row 693 : 2
 Total NaN in row 694 : 2
 Total NaN in row 695 : 0
 Total NaN in row 696 : 0
 Total NaN in row 697 : 9
 Total NaN in row 698 : 3
 Total NaN in row 699 : 9
 Total NaN in row 700 : 9
 Total NaN in row 701 : 1
 Total NaN in row 702 : 2
 Total NaN in row 703 : 0
 Total NaN in row 704 : 0
 Total NaN in row 705 : 1
 Total NaN in row 706 : 0
 Total NaN in row 707 : 9
 Total NaN in row 708 : 10
 Total NaN in row 709 : 2
 Total NaN in row 710 : 9
 Total NaN in row 711 : 0
 Total NaN in row 712 : 9
 Total NaN in row 713 : 9
 Total NaN in row 714 : 1
 Total NaN in row 715 : 0
 Total NaN in row 716 : 9
 Total NaN in row 717 : 1
 Total NaN in row 718 : 2
 Total NaN in row 719 : 9
 Total NaN in row 720 : 1
 Total NaN in row 721 : 1
 Total NaN in row 722 : 1
 Total NaN in row 723 : 0
 Total NaN in row 724 : 1
 Total NaN in row 725 : 0
 Total NaN in row 726 : 9
 Total NaN in row 727 : 10
 Total NaN in row 728 : 9
 Total NaN in row 729 : 10
 Total NaN in row 730 : 2
 Total NaN in row 731 : 0
 Total NaN in row 732 : 0
 Total NaN in row 733 : 10
 Total NaN in row 734 : 0
 Total NaN in row 735 : 9
 Total NaN in row 736 : 9
 Total NaN in row 737 : 10
 Total NaN in row 738 : 9
 Total NaN in row 739 : 10
 Total NaN in row 740 : 0
 Total NaN in row 741 : 1
 Total NaN in row 742 : 1
 Total NaN in row 743 : 1
 Total NaN in row 744 : 0
 Total NaN in row 745 : 3
 Total NaN in row 746 : 0
 Total NaN in row 747 : 1
 Total NaN in row 748 : 9
 Total NaN in row 749 : 0
 Total NaN in row 750 : 0
 Total NaN in row 751 : 0
 Total NaN in row 752 : 1
 Total NaN in row 753 : 2
 Total NaN in row 754 : 1
 Total NaN in row 755 : 0
 Total NaN in row 756 : 2
 Total NaN in row 757 : 2
 Total NaN in row 758 : 2
 Total NaN in row 759 : 9
 Total NaN in row 760 : 1
 Total NaN in row 761 : 0
 Total NaN in row 762 : 1
 Total NaN in row 763 : 2
 Total NaN in row 764 : 9
 Total NaN in row 765 : 2
 Total NaN in row 766 : 0
 Total NaN in row 767 : 2
 Total NaN in row 768 : 9
 Total NaN in row 769 : 9
 Total NaN in row 770 : 0
 Total NaN in row 771 : 1

In [61]:
for i in range(len(df.index)):
    print(" Total NaN in row", i, ":", 
          df.iloc[i].isnull().mean()*100)

 Total NaN in row 0 : 14.285714285714285
 Total NaN in row 1 : 9.523809523809524
 Total NaN in row 2 : 0.0
 Total NaN in row 3 : 14.285714285714285
 Total NaN in row 4 : 0.0
 Total NaN in row 5 : 9.523809523809524
 Total NaN in row 6 : 0.0
 Total NaN in row 7 : 4.761904761904762
 Total NaN in row 8 : 9.523809523809524
 Total NaN in row 9 : 9.523809523809524
 Total NaN in row 10 : 9.523809523809524
 Total NaN in row 11 : 0.0
 Total NaN in row 12 : 4.761904761904762
 Total NaN in row 13 : 4.761904761904762
 Total NaN in row 14 : 0.0
 Total NaN in row 15 : 42.857142857142854
 Total NaN in row 16 : 42.857142857142854
 Total NaN in row 17 : 9.523809523809524
 Total NaN in row 18 : 0.0
 Total NaN in row 19 : 42.857142857142854
 Total NaN in row 20 : 4.761904761904762
 Total NaN in row 21 : 42.857142857142854
 Total NaN in row 22 : 42.857142857142854
 Total NaN in row 23 : 9.523809523809524
 Total NaN in row 24 : 0.0
 Total NaN in row 25 : 0.0
 Total NaN in row 26 : 33.33333333333333
 Total NaN in row 27 : 42.857142857142854
 Total NaN in row 28 : 9.523809523809524
 Total NaN in row 29 : 9.523809523809524
 Total NaN in row 30 : 0.0
 Total NaN in row 31 : 100.0
 Total NaN in row 32 : 4.761904761904762
 Total NaN in row 33 : 0.0
 Total NaN in row 34 : 42.857142857142854
 Total NaN in row 35 : 47.61904761904761
 Total NaN in row 36 : 0.0
 Total NaN in row 37 : 9.523809523809524
 Total NaN in row 38 : 0.0
 Total NaN in row 39 : 0.0
 Total NaN in row 40 : 4.761904761904762
 Total NaN in row 41 : 4.761904761904762
 Total NaN in row 42 : 4.761904761904762
 Total NaN in row 43 : 0.0
 Total NaN in row 44 : 0.0
 Total NaN in row 45 : 0.0
 Total NaN in row 46 : 42.857142857142854
 Total NaN in row 47 : 42.857142857142854
 Total NaN in row 48 : 38.095238095238095
 Total NaN in row 49 : 9.523809523809524
 Total NaN in row 50 : 0.0
 Total NaN in row 51 : 4.761904761904762
 Total NaN in row 52 : 0.0
 Total NaN in row 53 : 42.857142857142854
 Total NaN in row 54 : 9.523809523809524
 Total NaN in row 55 : 33.33333333333333
 Total NaN in row 56 : 4.761904761904762
 Total NaN in row 57 : 0.0
 Total NaN in row 58 : 0.0
 Total NaN in row 59 : 0.0
 Total NaN in row 60 : 0.0
 Total NaN in row 61 : 47.61904761904761
 Total NaN in row 62 : 0.0
 Total NaN in row 63 : 42.857142857142854
 Total NaN in row 64 : 0.0
 Total NaN in row 65 : 38.095238095238095
 Total NaN in row 66 : 42.857142857142854
 Total NaN in row 67 : 0.0
 Total NaN in row 68 : 0.0
 Total NaN in row 69 : 0.0
 Total NaN in row 70 : 4.761904761904762
 Total NaN in row 71 : 0.0
 Total NaN in row 72 : 0.0
 Total NaN in row 73 : 0.0
 Total NaN in row 74 : 0.0
 Total NaN in row 75 : 42.857142857142854
 Total NaN in row 76 : 42.857142857142854
 Total NaN in row 77 : 42.857142857142854
 Total NaN in row 78 : 42.857142857142854
 Total NaN in row 79 : 42.857142857142854
 Total NaN in row 80 : 9.523809523809524
 Total NaN in row 81 : 4.761904761904762
 Total NaN in row 82 : 0.0
 Total NaN in row 83 : 0.0
 Total NaN in row 84 : 0.0
 Total NaN in row 85 : 42.857142857142854
 Total NaN in row 86 : 0.0
 Total NaN in row 87 : 0.0
 Total NaN in row 88 : 42.857142857142854
 Total NaN in row 89 : 0.0
 Total NaN in row 90 : 42.857142857142854
 Total NaN in row 91 : 0.0
 Total NaN in row 92 : 42.857142857142854
 Total NaN in row 93 : 42.857142857142854
 Total NaN in row 94 : 42.857142857142854
 Total NaN in row 95 : 9.523809523809524
 Total NaN in row 96 : 42.857142857142854
 Total NaN in row 97 : 9.523809523809524
 Total NaN in row 98 : 42.857142857142854
 Total NaN in row 99 : 0.0
 Total NaN in row 100 : 42.857142857142854
 Total NaN in row 101 : 0.0
 Total NaN in row 102 : 4.761904761904762
 Total NaN in row 103 : 9.523809523809524
 Total NaN in row 104 : 0.0
 Total NaN in row 105 : 0.0
 Total NaN in row 106 : 9.523809523809524
 Total NaN in row 107 : 0.0
 Total NaN in row 108 : 42.857142857142854
 Total NaN in row 109 : 0.0
 Total NaN in row 110 : 0.0
 Total NaN in row 111 : 9.523809523809524
 Total NaN in row 112 : 42.857142857142854
 Total NaN in row 113 : 0.0
 Total NaN in row 114 : 0.0
 Total NaN in row 115 : 0.0
 Total NaN in row 116 : 42.857142857142854
 Total NaN in row 117 : 9.523809523809524
 Total NaN in row 118 : 4.761904761904762
 Total NaN in row 119 : 9.523809523809524
 Total NaN in row 120 : 9.523809523809524
 Total NaN in row 121 : 9.523809523809524
 Total NaN in row 122 : 47.61904761904761
 Total NaN in row 123 : 9.523809523809524
 Total NaN in row 124 : 42.857142857142854
 Total NaN in row 125 : 42.857142857142854
 Total NaN in row 126 : 42.857142857142854
 Total NaN in row 127 : 42.857142857142854
 Total NaN in row 128 : 42.857142857142854
 Total NaN in row 129 : 9.523809523809524
 Total NaN in row 130 : 0.0
 Total NaN in row 131 : 42.857142857142854
 Total NaN in row 132 : 42.857142857142854
 Total NaN in row 133 : 42.857142857142854
 Total NaN in row 134 : 0.0
 Total NaN in row 135 : 9.523809523809524
 Total NaN in row 136 : 0.0
 Total NaN in row 137 : 0.0
 Total NaN in row 138 : 9.523809523809524
 Total NaN in row 139 : 0.0
 Total NaN in row 140 : 4.761904761904762
 Total NaN in row 141 : 4.761904761904762
 Total NaN in row 142 : 9.523809523809524
 Total NaN in row 143 : 0.0
 Total NaN in row 144 : 4.761904761904762
 Total NaN in row 145 : 9.523809523809524
 Total NaN in row 146 : 0.0
 Total NaN in row 147 : 42.857142857142854
 Total NaN in row 148 : 0.0
 Total NaN in row 149 : 9.523809523809524
 Total NaN in row 150 : 0.0
 Total NaN in row 151 : 4.761904761904762
 Total NaN in row 152 : 9.523809523809524
 Total NaN in row 153 : 0.0
 Total NaN in row 154 : 9.523809523809524
 Total NaN in row 155 : 9.523809523809524
 Total NaN in row 156 : 0.0
 Total NaN in row 157 : 9.523809523809524
 Total NaN in row 158 : 4.761904761904762
 Total NaN in row 159 : 9.523809523809524
 Total NaN in row 160 : 0.0
 Total NaN in row 161 : 14.285714285714285
 Total NaN in row 162 : 0.0
 Total NaN in row 163 : 0.0
 Total NaN in row 164 : 14.285714285714285
 Total NaN in row 165 : 14.285714285714285
 Total NaN in row 166 : 4.761904761904762
 Total NaN in row 167 : 0.0
 Total NaN in row 168 : 14.285714285714285
 Total NaN in row 169 : 0.0
 Total NaN in row 170 : 14.285714285714285
 Total NaN in row 171 : 9.523809523809524
 Total NaN in row 172 : 14.285714285714285
 Total NaN in row 173 : 0.0
 Total NaN in row 174 : 4.761904761904762
 Total NaN in row 175 : 14.285714285714285
 Total NaN in row 176 : 14.285714285714285
 Total NaN in row 177 : 0.0
 Total NaN in row 178 : 0.0
 Total NaN in row 179 : 0.0
 Total NaN in row 180 : 9.523809523809524
 Total NaN in row 181 : 9.523809523809524
 Total NaN in row 182 : 9.523809523809524
 Total NaN in row 183 : 9.523809523809524
 Total NaN in row 184 : 0.0
 Total NaN in row 185 : 42.857142857142854
 Total NaN in row 186 : 9.523809523809524
 Total NaN in row 187 : 0.0
 Total NaN in row 188 : 4.761904761904762
 Total NaN in row 189 : 4.761904761904762
 Total NaN in row 190 : 14.285714285714285
 Total NaN in row 191 : 9.523809523809524
 Total NaN in row 192 : 0.0
 Total NaN in row 193 : 9.523809523809524
 Total NaN in row 194 : 0.0
 Total NaN in row 195 : 4.761904761904762
 Total NaN in row 196 : 0.0
 Total NaN in row 197 : 4.761904761904762
 Total NaN in row 198 : 9.523809523809524
 Total NaN in row 199 : 42.857142857142854
 Total NaN in row 200 : 14.285714285714285
 Total NaN in row 201 : 42.857142857142854
 Total NaN in row 202 : 0.0
 Total NaN in row 203 : 0.0
 Total NaN in row 204 : 9.523809523809524
 Total NaN in row 205 : 0.0
 Total NaN in row 206 : 0.0
 Total NaN in row 207 : 9.523809523809524
 Total NaN in row 208 : 47.61904761904761
 Total NaN in row 209 : 42.857142857142854
 Total NaN in row 210 : 9.523809523809524
 Total NaN in row 211 : 9.523809523809524
 Total NaN in row 212 : 47.61904761904761
 Total NaN in row 213 : 42.857142857142854
 Total NaN in row 214 : 9.523809523809524
 Total NaN in row 215 : 0.0
 Total NaN in row 216 : 0.0
 Total NaN in row 217 : 0.0
 Total NaN in row 218 : 0.0
 Total NaN in row 219 : 9.523809523809524
 Total NaN in row 220 : 0.0
 Total NaN in row 221 : 33.33333333333333
 Total NaN in row 222 : 14.285714285714285
 Total NaN in row 223 : 42.857142857142854
 Total NaN in row 224 : 42.857142857142854
 Total NaN in row 225 : 9.523809523809524
 Total NaN in row 226 : 42.857142857142854
 Total NaN in row 227 : 0.0
 Total NaN in row 228 : 4.761904761904762
 Total NaN in row 229 : 9.523809523809524
 Total NaN in row 230 : 0.0
 Total NaN in row 231 : 0.0
 Total NaN in row 232 : 0.0
 Total NaN in row 233 : 0.0
 Total NaN in row 234 : 0.0
 Total NaN in row 235 : 9.523809523809524
 Total NaN in row 236 : 0.0
 Total NaN in row 237 : 0.0
 Total NaN in row 238 : 9.523809523809524
 Total NaN in row 239 : 0.0
 Total NaN in row 240 : 9.523809523809524
 Total NaN in row 241 : 42.857142857142854
 Total NaN in row 242 : 0.0
 Total NaN in row 243 : 0.0
 Total NaN in row 244 : 4.761904761904762
 Total NaN in row 245 : 0.0
 Total NaN in row 246 : 9.523809523809524
 Total NaN in row 247 : 0.0
 Total NaN in row 248 : 9.523809523809524
 Total NaN in row 249 : 4.761904761904762
 Total NaN in row 250 : 0.0
 Total NaN in row 251 : 9.523809523809524
 Total NaN in row 252 : 0.0
 Total NaN in row 253 : 42.857142857142854
 Total NaN in row 254 : 4.761904761904762
 Total NaN in row 255 : 42.857142857142854
 Total NaN in row 256 : 0.0
 Total NaN in row 257 : 42.857142857142854
 Total NaN in row 258 : 4.761904761904762
 Total NaN in row 259 : 9.523809523809524
 Total NaN in row 260 : 0.0
 Total NaN in row 261 : 9.523809523809524
 Total NaN in row 262 : 0.0
 Total NaN in row 263 : 0.0
 Total NaN in row 264 : 9.523809523809524
 Total NaN in row 265 : 0.0
 Total NaN in row 266 : 9.523809523809524
 Total NaN in row 267 : 42.857142857142854
 Total NaN in row 268 : 9.523809523809524
 Total NaN in row 269 : 9.523809523809524
 Total NaN in row 270 : 0.0
 Total NaN in row 271 : 14.285714285714285
 Total NaN in row 272 : 9.523809523809524
 Total NaN in row 273 : 9.523809523809524
 Total NaN in row 274 : 42.857142857142854
 Total NaN in row 275 : 4.761904761904762
 Total NaN in row 276 : 9.523809523809524
 Total NaN in row 277 : 0.0
 Total NaN in row 278 : 9.523809523809524
 Total NaN in row 279 : 0.0
 Total NaN in row 280 : 9.523809523809524
 Total NaN in row 281 : 9.523809523809524
 Total NaN in row 282 : 4.761904761904762
 Total NaN in row 283 : 0.0
 Total NaN in row 284 : 4.761904761904762
 Total NaN in row 285 : 0.0
 Total NaN in row 286 : 0.0
 Total NaN in row 287 : 42.857142857142854
 Total NaN in row 288 : 42.857142857142854
 Total NaN in row 289 : 9.523809523809524
 Total NaN in row 290 : 0.0
 Total NaN in row 291 : 9.523809523809524
 Total NaN in row 292 : 47.61904761904761
 Total NaN in row 293 : 0.0
 Total NaN in row 294 : 47.61904761904761
 Total NaN in row 295 : 9.523809523809524
 Total NaN in row 296 : 0.0
 Total NaN in row 297 : 42.857142857142854
 Total NaN in row 298 : 42.857142857142854
 Total NaN in row 299 : 42.857142857142854
 Total NaN in row 300 : 0.0
 Total NaN in row 301 : 42.857142857142854
 Total NaN in row 302 : 0.0
 Total NaN in row 303 : 42.857142857142854
 Total NaN in row 304 : 42.857142857142854
 Total NaN in row 305 : 42.857142857142854
 Total NaN in row 306 : 47.61904761904761
 Total NaN in row 307 : 0.0
 Total NaN in row 308 : 42.857142857142854
 Total NaN in row 309 : 42.857142857142854
 Total NaN in row 310 : 4.761904761904762
 Total NaN in row 311 : 9.523809523809524
 Total NaN in row 312 : 42.857142857142854
 Total NaN in row 313 : 42.857142857142854
 Total NaN in row 314 : 4.761904761904762
 Total NaN in row 315 : 9.523809523809524
 Total NaN in row 316 : 42.857142857142854
 Total NaN in row 317 : 47.61904761904761
 Total NaN in row 318 : 47.61904761904761
 Total NaN in row 319 : 42.857142857142854
 Total NaN in row 320 : 42.857142857142854
 Total NaN in row 321 : 42.857142857142854
 Total NaN in row 322 : 0.0
 Total NaN in row 323 : 0.0
 Total NaN in row 324 : 42.857142857142854
 Total NaN in row 325 : 42.857142857142854
 Total NaN in row 326 : 9.523809523809524
 Total NaN in row 327 : 42.857142857142854
 Total NaN in row 328 : 42.857142857142854
 Total NaN in row 329 : 42.857142857142854
 Total NaN in row 330 : 42.857142857142854
 Total NaN in row 331 : 42.857142857142854
 Total NaN in row 332 : 42.857142857142854
 Total NaN in row 333 : 42.857142857142854
 Total NaN in row 334 : 42.857142857142854
 Total NaN in row 335 : 9.523809523809524
 Total NaN in row 336 : 4.761904761904762
 Total NaN in row 337 : 42.857142857142854
 Total NaN in row 338 : 4.761904761904762
 Total NaN in row 339 : 9.523809523809524
 Total NaN in row 340 : 0.0
 Total NaN in row 341 : 0.0
 Total NaN in row 342 : 42.857142857142854
 Total NaN in row 343 : 0.0
 Total NaN in row 344 : 0.0
 Total NaN in row 345 : 4.761904761904762
 Total NaN in row 346 : 42.857142857142854
 Total NaN in row 347 : 9.523809523809524
 Total NaN in row 348 : 9.523809523809524
 Total NaN in row 349 : 47.61904761904761
 Total NaN in row 350 : 0.0
 Total NaN in row 351 : 9.523809523809524
 Total NaN in row 352 : 42.857142857142854
 Total NaN in row 353 : 42.857142857142854
 Total NaN in row 354 : 9.523809523809524
 Total NaN in row 355 : 42.857142857142854
 Total NaN in row 356 : 9.523809523809524
 Total NaN in row 357 : 0.0
 Total NaN in row 358 : 42.857142857142854
 Total NaN in row 359 : 47.61904761904761
 Total NaN in row 360 : 9.523809523809524
 Total NaN in row 361 : 9.523809523809524
 Total NaN in row 362 : 0.0
 Total NaN in row 363 : 42.857142857142854
 Total NaN in row 364 : 42.857142857142854
 Total NaN in row 365 : 14.285714285714285
 Total NaN in row 366 : 0.0
 Total NaN in row 367 : 9.523809523809524
 Total NaN in row 368 : 0.0
 Total NaN in row 369 : 0.0
 Total NaN in row 370 : 4.761904761904762
 Total NaN in row 371 : 42.857142857142854
 Total NaN in row 372 : 0.0
 Total NaN in row 373 : 9.523809523809524
 Total NaN in row 374 : 42.857142857142854
 Total NaN in row 375 : 42.857142857142854
 Total NaN in row 376 : 0.0
 Total NaN in row 377 : 14.285714285714285
 Total NaN in row 378 : 9.523809523809524
 Total NaN in row 379 : 14.285714285714285
 Total NaN in row 380 : 47.61904761904761
 Total NaN in row 381 : 0.0
 Total NaN in row 382 : 14.285714285714285
 Total NaN in row 383 : 9.523809523809524
 Total NaN in row 384 : 0.0
 Total NaN in row 385 : 47.61904761904761
 Total NaN in row 386 : 4.761904761904762
 Total NaN in row 387 : 9.523809523809524
 Total NaN in row 388 : 4.761904761904762
 Total NaN in row 389 : 4.761904761904762
 Total NaN in row 390 : 42.857142857142854
 Total NaN in row 391 : 9.523809523809524
 Total NaN in row 392 : 14.285714285714285
 Total NaN in row 393 : 0.0
 Total NaN in row 394 : 9.523809523809524
 Total NaN in row 395 : 9.523809523809524
 Total NaN in row 396 : 4.761904761904762
 Total NaN in row 397 : 4.761904761904762
 Total NaN in row 398 : 4.761904761904762
 Total NaN in row 399 : 47.61904761904761
 Total NaN in row 400 : 4.761904761904762
 Total NaN in row 401 : 0.0
 Total NaN in row 402 : 4.761904761904762
 Total NaN in row 403 : 0.0
 Total NaN in row 404 : 9.523809523809524
 Total NaN in row 405 : 4.761904761904762
 Total NaN in row 406 : 9.523809523809524
 Total NaN in row 407 : 4.761904761904762
 Total NaN in row 408 : 0.0
 Total NaN in row 409 : 4.761904761904762
 Total NaN in row 410 : 0.0
 Total NaN in row 411 : 0.0
 Total NaN in row 412 : 4.761904761904762
 Total NaN in row 413 : 4.761904761904762
 Total NaN in row 414 : 4.761904761904762
 Total NaN in row 415 : 9.523809523809524
 Total NaN in row 416 : 4.761904761904762
 Total NaN in row 417 : 0.0
 Total NaN in row 418 : 47.61904761904761
 Total NaN in row 419 : 0.0
 Total NaN in row 420 : 47.61904761904761
 Total NaN in row 421 : 9.523809523809524
 Total NaN in row 422 : 14.285714285714285
 Total NaN in row 423 : 4.761904761904762
 Total NaN in row 424 : 47.61904761904761
 Total NaN in row 425 : 14.285714285714285
 Total NaN in row 426 : 9.523809523809524
 Total NaN in row 427 : 0.0
 Total NaN in row 428 : 4.761904761904762
 Total NaN in row 429 : 9.523809523809524
 Total NaN in row 430 : 9.523809523809524
 Total NaN in row 431 : 9.523809523809524
 Total NaN in row 432 : 9.523809523809524
 Total NaN in row 433 : 0.0
 Total NaN in row 434 : 47.61904761904761
 Total NaN in row 435 : 9.523809523809524
 Total NaN in row 436 : 4.761904761904762
 Total NaN in row 437 : 4.761904761904762
 Total NaN in row 438 : 9.523809523809524
 Total NaN in row 439 : 0.0
 Total NaN in row 440 : 4.761904761904762
 Total NaN in row 441 : 9.523809523809524
 Total NaN in row 442 : 0.0
 Total NaN in row 443 : 47.61904761904761
 Total NaN in row 444 : 47.61904761904761
 Total NaN in row 445 : 0.0
 Total NaN in row 446 : 0.0
 Total NaN in row 447 : 14.285714285714285
 Total NaN in row 448 : 14.285714285714285
 Total NaN in row 449 : 14.285714285714285
 Total NaN in row 450 : 9.523809523809524
 Total NaN in row 451 : 4.761904761904762
 Total NaN in row 452 : 42.857142857142854
 Total NaN in row 453 : 9.523809523809524
 Total NaN in row 454 : 0.0
 Total NaN in row 455 : 4.761904761904762
 Total NaN in row 456 : 0.0
 Total NaN in row 457 : 4.761904761904762
 Total NaN in row 458 : 0.0
 Total NaN in row 459 : 9.523809523809524
 Total NaN in row 460 : 4.761904761904762
 Total NaN in row 461 : 14.285714285714285
 Total NaN in row 462 : 0.0
 Total NaN in row 463 : 42.857142857142854
 Total NaN in row 464 : 47.61904761904761
 Total NaN in row 465 : 42.857142857142854
 Total NaN in row 466 : 0.0
 Total NaN in row 467 : 0.0
 Total NaN in row 468 : 0.0
 Total NaN in row 469 : 0.0
 Total NaN in row 470 : 14.285714285714285
 Total NaN in row 471 : 4.761904761904762
 Total NaN in row 472 : 9.523809523809524
 Total NaN in row 473 : 14.285714285714285
 Total NaN in row 474 : 0.0
 Total NaN in row 475 : 42.857142857142854
 Total NaN in row 476 : 4.761904761904762
 Total NaN in row 477 : 14.285714285714285
 Total NaN in row 478 : 42.857142857142854
 Total NaN in row 479 : 9.523809523809524
 Total NaN in row 480 : 9.523809523809524
 Total NaN in row 481 : 0.0
 Total NaN in row 482 : 9.523809523809524
 Total NaN in row 483 : 14.285714285714285
 Total NaN in row 484 : 4.761904761904762
 Total NaN in row 485 : 4.761904761904762
 Total NaN in row 486 : 9.523809523809524
 Total NaN in row 487 : 0.0
 Total NaN in row 488 : 0.0
 Total NaN in row 489 : 4.761904761904762
 Total NaN in row 490 : 42.857142857142854
 Total NaN in row 491 : 0.0
 Total NaN in row 492 : 0.0
 Total NaN in row 493 : 0.0
 Total NaN in row 494 : 4.761904761904762
 Total NaN in row 495 : 0.0
 Total NaN in row 496 : 0.0
 Total NaN in row 497 : 0.0
 Total NaN in row 498 : 0.0
 Total NaN in row 499 : 42.857142857142854
 Total NaN in row 500 : 0.0
 Total NaN in row 501 : 0.0
 Total NaN in row 502 : 0.0
 Total NaN in row 503 : 9.523809523809524
 Total NaN in row 504 : 0.0
 Total NaN in row 505 : 0.0
 Total NaN in row 506 : 4.761904761904762
 Total NaN in row 507 : 0.0
 Total NaN in row 508 : 14.285714285714285
 Total NaN in row 509 : 0.0
 Total NaN in row 510 : 9.523809523809524
 Total NaN in row 511 : 9.523809523809524
 Total NaN in row 512 : 42.857142857142854
 Total NaN in row 513 : 0.0
 Total NaN in row 514 : 42.857142857142854
 Total NaN in row 515 : 4.761904761904762
 Total NaN in row 516 : 0.0
 Total NaN in row 517 : 9.523809523809524
 Total NaN in row 518 : 4.761904761904762
 Total NaN in row 519 : 42.857142857142854
 Total NaN in row 520 : 0.0
 Total NaN in row 521 : 9.523809523809524
 Total NaN in row 522 : 4.761904761904762
 Total NaN in row 523 : 4.761904761904762
 Total NaN in row 524 : 4.761904761904762
 Total NaN in row 525 : 42.857142857142854
 Total NaN in row 526 : 0.0
 Total NaN in row 527 : 0.0
 Total NaN in row 528 : 0.0
 Total NaN in row 529 : 0.0
 Total NaN in row 530 : 42.857142857142854
 Total NaN in row 531 : 0.0
 Total NaN in row 532 : 0.0
 Total NaN in row 533 : 42.857142857142854
 Total NaN in row 534 : 0.0

In [ ]:
# 9. Determine the column names having more than 30% missing values and remove them from the dataset.

In [67]:
df_n=df.isnull().sum()
col=df.columns
for i in range(len(df_n)):
    if df_n[i]>7110:  #7110 is 30% of total data
        print(i,col[i],':'," REMOVE the dataset \n")
    else:
        print(i,col[i],':', 'Need to use mean or mode to fill \n')

0 Suburb : Need to use mean or mode to fill

1 Address : Need to use mean or mode to fill

2 Rooms : Need to use mean or mode to fill

3 Type : Need to use mean or mode to fill

4 Price : Need to use mean or mode to fill

5 Method : Need to use mean or mode to fill

6 SellerG : Need to use mean or mode to fill

7 Date : Need to use mean or mode to fill

8 Distance : Need to use mean or mode to fill

9 Postcode : Need to use mean or mode to fill

10 Bedroom2 : Need to use mean or mode to fill

11 Bathroom : Need to use mean or mode to fill

12 Car : Need to use mean or mode to fill

13 Landsize : Need to use mean or mode to fill

14 BuildingArea :  REMOVE the dataset

15 YearBuilt :  REMOVE the dataset

16 CouncilArea :  REMOVE the dataset

17 Lattitude : Need to use mean or mode to fill

18 Longtitude : Need to use mean or mode to fill

19 Regionname : Need to use mean or mode to fill

20 Propertycount : Need to use mean or mode to fill

In [75]:
df_n=df.isnull().sum()
col=df.columns
for i in range(len(df_n)):
    if df_n[i]>7110:  #7110 is 30% of total data
        print(i,col[i],':'," REMOVE the dataset \n")
        df[col[i]]=df[col[i]].dropna()
    else:
        print(i,col[i],':', 'Need to use mean or mode to fill \n')

0 Suburb : Need to use mean or mode to fill

1 Address : Need to use mean or mode to fill

2 Rooms : Need to use mean or mode to fill

3 Type : Need to use mean or mode to fill

4 Price : Need to use mean or mode to fill

5 Method : Need to use mean or mode to fill

6 SellerG : Need to use mean or mode to fill

7 Date : Need to use mean or mode to fill

8 Distance : Need to use mean or mode to fill

9 Postcode : Need to use mean or mode to fill

10 Bedroom2 : Need to use mean or mode to fill

11 Bathroom : Need to use mean or mode to fill

12 Car : Need to use mean or mode to fill

13 Landsize : Need to use mean or mode to fill

14 BuildingArea :  REMOVE the dataset

15 YearBuilt :  REMOVE the dataset

16 CouncilArea :  REMOVE the dataset

17 Lattitude : Need to use mean or mode to fill

18 Longtitude : Need to use mean or mode to fill

19 Regionname : Need to use mean or mode to fill

20 Propertycount : Need to use mean or mode to fill

In [77]:
df['BuildingArea']=df['BuildingArea'].dropna()
df['YearBuilt']=df['YearBuilt'].dropna()
df['CouncilArea']=df['CouncilArea'].dropna()

In [ ]:
#10. Determine the number and percentage of rows having more than 5 missing values. 
#    If the percentage of such rows is less than 20% then remove all these rows.

In [93]:
ab=df.iloc[i].isnull().sum()
for i in range(len(df.index)):
    if df.iloc[i].isnull().sum()>5:
        print(i,'MORE than 5')
        if df.iloc[i].isnull().mean()*100 >20.0:
            [df.iloc[i]]=[df.iloc[i]].dropna()
    else:
        print(i,'Missing value less than 5')

0 Missing value less than 5
1 Missing value less than 5
2 Missing value less than 5
3 Missing value less than 5
4 Missing value less than 5
5 Missing value less than 5
6 Missing value less than 5
7 Missing value less than 5
8 Missing value less than 5
9 Missing value less than 5
10 Missing value less than 5
11 Missing value less than 5
12 Missing value less than 5
13 Missing value less than 5
14 Missing value less than 5
15 MORE than 5

AttributeError: 'list' object has no attribute 'dropna'

In [92]:
df.isnull().sum().dropna

<bound method Series.dropna of Suburb             131
Address            131
Rooms              131
Type               131
Price             5282
Method             131
SellerG            131
Date               131
Distance           132
Postcode           132
Bedroom2          4612
Bathroom          4615
Car               4757
Landsize          6268
BuildingArea     13660
YearBuilt        12138
CouncilArea       8022
Lattitude         4435
Longtitude        4435
Regionname         132
Propertycount      132
dtype: int64>

In [65]:
df.isnull().sum()

Suburb             131
Address            131
Rooms              131
Type               131
Price             5282
Method             131
SellerG            131
Date               131
Distance           132
Postcode           132
Bedroom2          4612
Bathroom          4615
Car               4757
Landsize          6268
BuildingArea     13660
YearBuilt        12138
CouncilArea       8022
Lattitude         4435
Longtitude        4435
Regionname         132
Propertycount      132
dtype: int64

In [55]:
df.index

RangeIndex(start=0, stop=23678, step=1)

In [20]:
df.isnull().mean()*100

Suburb            0.553256
Address           0.553256
Rooms             0.553256
Type              0.553256
Price            22.307627
Method            0.553256
SellerG           0.553256
Date              0.553256
Distance          0.557480
Postcode          0.557480
Bedroom2         19.477996
Bathroom         19.490666
Car              20.090379
Landsize         26.471830
BuildingArea     57.690683
YearBuilt        51.262776
CouncilArea      33.879551
Lattitude        18.730467
Longtitude       18.730467
Regionname        0.557480
Propertycount     0.557480
dtype: float64

In [21]:
percent_missing = df.isnull().sum() * 100 / len(df)
percent_missing

Suburb            0.553256
Address           0.553256
Rooms             0.553256
Type              0.553256
Price            22.307627
Method            0.553256
SellerG           0.553256
Date              0.553256
Distance          0.557480
Postcode          0.557480
Bedroom2         19.477996
Bathroom         19.490666
Car              20.090379
Landsize         26.471830
BuildingArea     57.690683
YearBuilt        51.262776
CouncilArea      33.879551
Lattitude        18.730467
Longtitude       18.730467
Regionname        0.557480
Propertycount     0.557480
dtype: float64

In [22]:
missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 'percent_missing': percent_missing})
missing_value_df

                 column_name  percent_missing
Suburb                Suburb         0.553256
Address              Address         0.553256
Rooms                  Rooms         0.553256
Type                    Type         0.553256
Price                  Price        22.307627
Method                Method         0.553256
SellerG              SellerG         0.553256
Date                    Date         0.553256
Distance            Distance         0.557480
Postcode            Postcode         0.557480
Bedroom2            Bedroom2        19.477996
Bathroom            Bathroom        19.490666
Car                      Car        20.090379
Landsize            Landsize        26.471830
BuildingArea    BuildingArea        57.690683
YearBuilt          YearBuilt        51.262776
CouncilArea      CouncilArea        33.879551
Lattitude          Lattitude        18.730467
Longtitude        Longtitude        18.730467
Regionname        Regionname         0.557480
Propertycount  Propertycount         0.557480

In [23]:
len(col)

21

In [24]:
len(df_n)

TypeError: object of type 'numpy.int32' has no len()